export const EVENTS = {
  MISSION_CREATED: "MISSION_CREATED",
  MISSION_UPDATED: "MISSION_UPDATED",
  CONTACT_CREATED: "CONTACT_CREATED",
  KNOWLEDGE_ADDED: "KNOWLEDGE_ADDED",
  OPPORTUNITY_CREATED: "OPPORTUNITY_CREATED",
  MEETING_LOGGED: "MEETING_LOGGED",
  CONTENT_CREATED: "CONTENT_CREATED",
  NOTIFICATION_EMITTED: "NOTIFICATION_EMITTED"
};
